config/routes.rb
Rails.application.routes.draw do
  resources :coupons

  resources :subscribers

  resources :rsvps

  resources :forms

  resources :events

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = Rsvp.all
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
  end

  # GET /rsvps/new
  def new
    @rsvp = Rsvp.new
  end

  # GET /rsvps/1/edit
  def edit
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(rsvp_params)

    respond_to do |format|
      if @rsvp.save
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html { render :new }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rsvps/1
  # PATCH/PUT /rsvps/1.json
  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to rsvps_url, notice: 'Rsvp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.require(:rsvp).permit(:subscriber_id, :form_id, :success, :attempts, :last_attempt)
    end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subscriber_id %><br>
    <%= f.number_field :subscriber_id %>
  </div>
  <div class="field">
    <%= f.label :form_id %><br>
    <%= f.number_field :form_id %>
  </div>
  <div class="field">
    <%= f.label :success %><br>
    <%= f.check_box :success %>
  </div>
  <div class="field">
    <%= f.label :attempts %><br>
    <%= f.number_field :attempts %>
  </div>
  <div class="field">
    <%= f.label :last_attempt %><br>
    <%= f.datetime_select :last_attempt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Editing rsvp</h1>

<%= render 'form' %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<h1>Listing rsvps</h1>

<table>
  <thead>
    <tr>
      <th>Subscriber</th>
      <th>Form</th>
      <th>Success</th>
      <th>Attempts</th>
      <th>Last attempt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsvps.each do |rsvp| %>
      <tr>
        <td><%= rsvp.subscriber_id %></td>
        <td><%= rsvp.form_id %></td>
        <td><%= rsvp.success %></td>
        <td><%= rsvp.attempts %></td>
        <td><%= rsvp.last_attempt %></td>
        <td><%= link_to 'Show', rsvp %></td>
        <td><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
        <td><%= link_to 'Destroy', rsvp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rsvp', new_rsvp_path %>

app/views/rsvps/new.html.erb
<h1>New rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subscriber:</strong>
  <%= @rsvp.subscriber_id %>
</p>

<p>
  <strong>Form:</strong>
  <%= @rsvp.form_id %>
</p>

<p>
  <strong>Success:</strong>
  <%= @rsvp.success %>
</p>

<p>
  <strong>Attempts:</strong>
  <%= @rsvp.attempts %>
</p>

<p>
  <strong>Last attempt:</strong>
  <%= @rsvp.last_attempt %>
</p>

<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<%= link_to 'Back', rsvps_path %>