config/routes.rb
Rails.application.routes.draw do
  resources :coupons

  resources :subscribers

  resources :rsvps

  resources :forms

  resources :events

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:first_name, :last_name, :address1, :address2, :city, :state, :zip, :email, :fake_email, :affiliation, :phone, :coupon_id, :type_id, :date_joined)
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :fake_email %><br>
    <%= f.text_field :fake_email %>
  </div>
  <div class="field">
    <%= f.label :affiliation %><br>
    <%= f.text_field :affiliation %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :coupon_id %><br>
    <%= f.text_field :coupon_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.text_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :date_joined %><br>
    <%= f.datetime_select :date_joined %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Fake email</th>
      <th>Affiliation</th>
      <th>Phone</th>
      <th>Coupon</th>
      <th>Type</th>
      <th>Date joined</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.first_name %></td>
        <td><%= subscriber.last_name %></td>
        <td><%= subscriber.address1 %></td>
        <td><%= subscriber.address2 %></td>
        <td><%= subscriber.city %></td>
        <td><%= subscriber.state %></td>
        <td><%= subscriber.zip %></td>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.fake_email %></td>
        <td><%= subscriber.affiliation %></td>
        <td><%= subscriber.phone %></td>
        <td><%= subscriber.coupon_id %></td>
        <td><%= subscriber.type_id %></td>
        <td><%= subscriber.date_joined %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @subscriber.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @subscriber.last_name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @subscriber.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @subscriber.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @subscriber.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @subscriber.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @subscriber.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<p>
  <strong>Fake email:</strong>
  <%= @subscriber.fake_email %>
</p>

<p>
  <strong>Affiliation:</strong>
  <%= @subscriber.affiliation %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @subscriber.phone %>
</p>

<p>
  <strong>Coupon:</strong>
  <%= @subscriber.coupon_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @subscriber.type_id %>
</p>

<p>
  <strong>Date joined:</strong>
  <%= @subscriber.date_joined %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>